[workspace]
authors = ["Mohamed-Badry <m.badry.fl@gmail.com>"]
channels = ["conda-forge"]
name = "gr_sat"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
gnuradio = ">=3.10.12.0,<4"
gnuradio-satellites = ">=5.9.0,<6"
numpy = ">=2.4.1,<3"
pandas = ">=3.0.0,<4"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.17.0,<2"
scikit-learn = ">=1.8.0,<2"
ipykernel = ">=7.1.0,<8"
ipywidgets = ">=8.1.8,<9"
nbconvert = ">=7.16.6,<8"
python-dotenv = ">=1.2.1,<2"
seaborn = ">=0.13.2,<0.14"
skyfield = ">=1.54,<2"
requests = ">=2.32.5,<3"
tqdm = ">=4.67.2,<5"
just = ">=1.46.0,<2"
loguru = ">=0.7.3,<0.8"
rich = ">=14.3.2,<15"

[pypi-dependencies]
gr_sat = { path = ".", editable = true }
pyax25 = ">=1.0.0, <2"
construct = ">=2.10"